"""
Tenant configuration encryption — Fernet (AES-128-CBC) for secrets at rest.

Uses a TENANT_ENCRYPTION_KEY env var to encrypt/decrypt all tenant config
blobs stored in the tenants table. This protects multi-org credentials
(Wazuh passwords, API keys, Slack webhooks) at rest in the Postgres database.

Versioned ciphertext (M2 item 3)
--------------------------------
Ciphertext is stored as ``v<N>:<fernet_token>``. The ``v<N>`` tag records the
master *generation* a token was encrypted under. An untagged token is treated
as generation 1 (legacy data written before this scheme).

Two master generations can be active at once during rotation:
  - ``TENANT_ENCRYPTION_KEY``      — the new/current master (CURRENT_GENERATION)
  - ``TENANT_ENCRYPTION_KEY_OLD``  — the previous master (CURRENT_GENERATION-1)

``encrypt_config`` ALWAYS writes the current generation. ``decrypt_config`` can
resolve BOTH generations, so every row is readable at every instant of a
rotation (no unreadable window). A Fernet token is key-bound: a gen-1 token
returns ``InvalidToken`` under the gen-2 key, so no single row is ever
decryptable by two generations — the tag just makes selection explicit.

The current generation is **env-driven** via ``TENANT_KEY_GENERATION`` (default
1). EACH rotation bumps it, so a 2nd/3rd rotation correctly advances the
``v<N>:`` tag (1→2→3 …). At every generation N, ``TENANT_ENCRYPTION_KEY`` is the
gen-N master and ``TENANT_ENCRYPTION_KEY_OLD`` is the gen-(N-1) master. Older
generations than N-1 are intentionally NOT resolvable (they fail closed) — a
rotation must complete its re-encrypt sweep before the next one starts.

Writes fail closed on a non-persistent master (WO-H75)
------------------------------------------------------
``_get_fernet`` still auto-generates a throwaway master in single-tenant mode
when ``TENANT_ENCRYPTION_KEY`` is missing/invalid, so a READ in a shell that
never sourced ``.env`` keeps behaving as before: it produces the usual
``TenantCryptoError`` from ``decrypt_config`` and callers fail closed.

A WRITE under such a key is unrecoverable — the key exists only in that
process's memory, so the row it stores can never be decrypted again. So
``encrypt_config`` refuses (``TenantCryptoError``) whenever the current
generation's master is missing, invalid, or was auto-generated in-process, in
EVERY deployment mode. The guard lives here rather than at the five call sites
that write tenant configs so the next writer added is covered automatically.
"""

import json
import os
import structlog
from cryptography.fernet import Fernet, InvalidToken

logger = structlog.get_logger(__name__)


def _current_generation() -> int:
    """The generation ``TENANT_ENCRYPTION_KEY`` represents / ``encrypt_config``
    writes, read from ``TENANT_KEY_GENERATION`` (default 1).

    Read at call time (not import time) so a rotation that bumps the env var
    plus ``_reset_fernet_cache()`` takes effect without a process restart, and
    so tests can advance the generation.
    """
    raw = os.environ.get("TENANT_KEY_GENERATION", "1")
    try:
        gen = int(raw)
    except (TypeError, ValueError):
        logger.warning("tenant_key_generation_invalid",
                       value=raw, msg="TENANT_KEY_GENERATION not an int — using 1")
        return 1
    return gen if gen >= 1 else 1


# Back-compat module attribute. NOTE: this is a snapshot taken at import time;
# code paths use the live ``_current_generation()`` instead. Kept so existing
# callers/tests that read ``CURRENT_GENERATION`` for the *import-time* value
# still work.
CURRENT_GENERATION = _current_generation()

# Cache of master Fernet instances keyed by generation number.
_fernet_by_gen: dict = {}

# The master-key VALUE each cached Fernet was built for, so the cache can be
# invalidated when the key changes underneath it. Recorded AFTER construction,
# so the auto-generate paths tag themselves with whatever ends up in the
# environment and keep caching exactly as before (one warning, not one per
# read) — while a genuine key change still invalidates.
_fernet_env_tag: dict = {}

# Master keys this PROCESS invented for itself (single-tenant auto-generate
# paths in ``_get_fernet``). They are never persisted, so anything encrypted
# under one is lost when the process exits — ``encrypt_config`` refuses them.
# Deliberately NOT cleared by ``_reset_fernet_cache``: forgetting that a key
# was invented would re-open the write hole this set exists to close.
_autogenerated_master_keys: set = set()

# How an operator mints a real master key. Repeated verbatim in the guard
# messages so the fix is in the error the operator actually sees.
_GENERATE_HINT = (
    "Generate one with: python -c \"from cryptography.fernet import Fernet; "
    "print(Fernet.generate_key().decode())\" and add it to your .env file."
)


class TenantCryptoError(ValueError):
    """Raised when a tenant config cannot be decrypted (fail-closed signal).

    Also raised by ``encrypt_config`` when the master key is not usable for a
    durable write (missing, invalid, or auto-generated in-process).
    """


def _master_key_for_gen(generation: int) -> str:
    """Return the raw master key string for a generation, or "" if unset.

    The CURRENT generation maps to ``TENANT_ENCRYPTION_KEY``; the previous
    generation maps to ``TENANT_ENCRYPTION_KEY_OLD``. Other generations are not
    configurable at runtime.
    """
    cur = _current_generation()
    if generation == cur:
        return os.environ.get("TENANT_ENCRYPTION_KEY", "")
    if generation == cur - 1:
        return os.environ.get("TENANT_ENCRYPTION_KEY_OLD", "")
    return ""


def _cache_fernet(generation: int, f: Fernet) -> None:
    """Cache ``f`` for ``generation``, tagged with the master key now in effect.

    Read at cache time rather than passed in: the single-tenant auto-generate
    path rewrites ``os.environ`` mid-call, and the invalid-key path leaves the
    bad value in place. Tagging with what is actually there afterwards keeps
    both stable across calls while still invalidating on a real key change.
    """
    _fernet_by_gen[generation] = f
    _fernet_env_tag[generation] = _master_key_for_gen(generation)


def _get_fernet(generation: int = None) -> Fernet:
    """Get or initialize the master Fernet cipher for a generation.

    In multi-tenant mode, refuses to start with a missing or invalid CURRENT
    key to prevent data loss (encrypted configs become undecryptable after
    restart). In single-tenant mode, auto-generates a key with a warning for
    backward compat. Non-current generations (e.g. the OLD rotation key) must
    be explicitly configured; if absent a KeyError is raised so the caller can
    fall through to the current generation.

    An auto-generated key is only ever good enough for a READ that is going to
    fail closed anyway; every such key is recorded in
    ``_autogenerated_master_keys`` so ``encrypt_config`` can refuse to persist
    ciphertext under it (WO-H75).
    """
    if generation is None:
        generation = _current_generation()
    cached = _fernet_by_gen.get(generation)
    if cached is not None:
        # Only reuse it if the master it was built for is still the master.
        # A cipher cached from an earlier auto-generated key would otherwise
        # outlive the key change and encrypt under the invented key while
        # _assert_master_key_writable was validating the real one.
        if _fernet_env_tag.get(generation) == _master_key_for_gen(generation):
            return cached
        _fernet_by_gen.pop(generation, None)
        _fernet_env_tag.pop(generation, None)

    from src.database.store import is_multi_tenant
    _is_mt = is_multi_tenant()

    key = _master_key_for_gen(generation)

    if generation != _current_generation():
        # Rotation/old generations are optional. Absence is not fatal.
        if not key:
            raise KeyError(f"no master key configured for generation {generation}")
        try:
            f = Fernet(key.encode() if isinstance(key, str) else key)
        except Exception as e:
            raise RuntimeError(
                f"TENANT_ENCRYPTION_KEY_OLD (generation {generation}) is not a "
                f"valid Fernet key: {e}")
        _cache_fernet(generation, f)
        return f

    # ── current generation (TENANT_ENCRYPTION_KEY) ──
    if not key:
        if _is_mt:
            raise RuntimeError(
                "FATAL: TENANT_ENCRYPTION_KEY is required in multi-tenant mode. "
                "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\" "
                "and add it to your .env file."
            )
        # Single-tenant: auto-generate and warn. Read-only value — writes are
        # refused by _assert_master_key_writable().
        key = Fernet.generate_key().decode()
        _autogenerated_master_keys.add(key)
        logger.warning(
            "tenant_encryption_key_generated",
            message="No TENANT_ENCRYPTION_KEY set. Generated a process-local "
                    "key: existing tenant configs will NOT decrypt and "
                    "writing new ones is refused. Set TENANT_ENCRYPTION_KEY "
                    "in your .env file.")
        os.environ["TENANT_ENCRYPTION_KEY"] = key

    try:
        f = Fernet(key.encode() if isinstance(key, str) else key)
    except Exception:
        if _is_mt:
            raise RuntimeError(
                "FATAL: TENANT_ENCRYPTION_KEY is not a valid Fernet key. "
                "Previously encrypted tenant configs will be undecryptable. "
                "Fix the key in your .env file before restarting."
            )
        # NOTE — the cache tag is NOT provenance on this branch. os.environ
        # still holds the INVALID string, so _cache_fernet below tags this
        # entry with that invalid string while the cipher itself was built
        # from the invented key. Every other branch satisfies
        # "tag == the key the cipher was built from"; this one does not.
        #
        # That is deliberate: the tag's job is "has the operator changed the
        # key since we cached?", and tagging with what is actually in the
        # environment is what keeps this path caching once instead of minting
        # a new key and re-logging on every read. It is only SAFE because
        # _assert_master_key_writable rejects an invalid key in encrypt_config
        # before the cache is ever consulted, so this cipher can serve reads
        # (which fail closed anyway) but can never write. Do not read the tag
        # as "the key this Fernet uses" — add a real provenance field if you
        # ever need that.
        key = Fernet.generate_key().decode()
        _autogenerated_master_keys.add(key)
        f = Fernet(key.encode())
        logger.error(
            "tenant_encryption_key_invalid",
            message="TENANT_ENCRYPTION_KEY is not a valid Fernet key. "
                    "Generated a process-local key for reads (which will "
                    "fail closed); writing tenant configs is refused until "
                    "the real key is restored in your .env file.")

    _cache_fernet(generation, f)
    return f


def _assert_master_key_writable(generation: int) -> None:
    """Fail closed unless ``generation``'s master key is durable (WO-H75).

    A write is only safe if the master key outlives this process. Refuse when
    ``TENANT_ENCRYPTION_KEY`` is:
      * unset — nothing to encrypt under but an invented key;
      * invalid — ``_get_fernet`` would swap in an invented replacement AND the
        real, existing rows would stop being readable;
      * a key this process invented earlier (a read may already have cached one
        into ``os.environ``, which would otherwise look like a configured key).

    Applies in EVERY deployment mode. Reads are untouched — this is called
    only from ``encrypt_config``.
    """
    key = _master_key_for_gen(generation)

    if not key:
        logger.error(
            "tenant_config_encrypt_refused",
            generation=generation, reason="master_key_missing",
            message="Refusing to encrypt a tenant config: "
                    "TENANT_ENCRYPTION_KEY is not set.")
        raise TenantCryptoError(
            "FATAL: TENANT_ENCRYPTION_KEY is required to encrypt tenant "
            "configs. Refusing to write — a config encrypted under a "
            "process-local key is permanently undecryptable once this process "
            "exits. " + _GENERATE_HINT)

    if key in _autogenerated_master_keys:
        logger.error(
            "tenant_config_encrypt_refused",
            generation=generation, reason="master_key_autogenerated",
            message="Refusing to encrypt a tenant config: the current "
                    "TENANT_ENCRYPTION_KEY was auto-generated in-process.")
        raise TenantCryptoError(
            "FATAL: TENANT_ENCRYPTION_KEY was auto-generated by this process "
            "and is not persisted anywhere. Refusing to write — the config "
            "would be permanently undecryptable once this process exits. "
            + _GENERATE_HINT)

    try:
        Fernet(key.encode() if isinstance(key, str) else key)
    except Exception as e:
        logger.error(
            "tenant_config_encrypt_refused",
            generation=generation, reason="master_key_invalid", error=str(e))
        raise TenantCryptoError(
            "FATAL: TENANT_ENCRYPTION_KEY is not a valid Fernet key. Refusing "
            "to write — encrypting under a replacement key would leave the "
            "tenant configs already stored under the real key undecryptable. "
            "Restore the correct key in your .env file (do NOT generate a new "
            "one to clear this error).")


def _reset_fernet_cache():
    """Clear the master Fernet cache and re-snapshot CURRENT_GENERATION.

    Call after any env change (notably ``TENANT_KEY_GENERATION``,
    ``TENANT_ENCRYPTION_KEY``, ``TENANT_ENCRYPTION_KEY_OLD``) so the new
    generation/keys take effect without a process restart. Refreshing the
    ``CURRENT_GENERATION`` module attribute keeps back-compat readers in sync.
    """
    global CURRENT_GENERATION
    _fernet_by_gen.clear()
    _fernet_env_tag.clear()
    CURRENT_GENERATION = _current_generation()


def _derive_tenant_fernet(tenant_id: str, generation: int = None) -> Fernet:
    """Derive a per-tenant Fernet key from a master generation using HKDF."""
    import base64
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF
    from cryptography.hazmat.primitives import hashes

    if generation is None:
        generation = _current_generation()

    # Ensure the requested generation's master is loadable (raises KeyError
    # if an old generation isn't configured).
    _get_fernet(generation)
    master_str = _master_key_for_gen(generation)
    master_key = base64.urlsafe_b64decode(master_str.encode())
    derived = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=None,
        info=f"dhruva-tenant-{tenant_id}".encode(),
    ).derive(master_key)
    # Fernet key = url-safe base64 of 32 bytes
    fernet_key = base64.urlsafe_b64encode(derived)
    return Fernet(fernet_key)


def _split_version(encrypted: str) -> tuple[int, str]:
    """Parse a ``v<N>:<token>`` tag. Untagged tokens are generation 1."""
    if encrypted[:1] == "v":
        head, sep, rest = encrypted.partition(":")
        if sep and head[1:].isdigit():
            return int(head[1:]), rest
    return 1, encrypted


def is_current_generation(encrypted: str, tenant_id: str = None) -> bool:
    """Return True if a token is already at the CURRENT generation.

    Used by the rotation tool for idempotency: a token is "current" iff it is
    tagged ``v<CURRENT_GENERATION>:`` AND it decrypts under the current master
    alone (not via the OLD rotation key). A token written under the old master
    but coincidentally carrying the current tag would fail the decrypt check.
    """
    if not encrypted:
        return True  # nothing to rotate
    cur = _current_generation()
    gen, token = _split_version(encrypted)
    if gen != cur:
        return False
    token_bytes = token.encode("utf-8")
    # Try the CURRENT generation only (per-tenant derived, then global).
    candidates = []
    if tenant_id:
        try:
            candidates.append(_derive_tenant_fernet(tenant_id, cur))
        except Exception as e:                       # noqa: BLE001
            # WO-H90: was a bare `except: pass`. A failure here drops the
            # per-tenant candidate, so the rotation tool reports "this token
            # needs rotating" when the truth is "we could not build the key to
            # check". DELIBERATELY does NOT log tenant_id, key material or the
            # token — only whether a tenant was in play, the generation, and a
            # truncated error. Same discipline as the encrypt-refusal logs above.
            logger.warning("tenant_generation_check_derive_failed",
                           generation=cur, has_tenant_id=True,
                           error=str(e)[:200])
    try:
        candidates.append(_get_fernet(cur))
    except Exception as e:                               # noqa: BLE001
        # WO-H90: was a bare `except: pass`. A failure here drops the global
        # candidate too — with both gone the answer is a flat "not current",
        # which an operator reads as "rotate it" rather than "your current
        # master key is missing or invalid". No key material or tenant
        # identifier in the event, by design.
        logger.warning("tenant_generation_check_master_key_failed",
                       generation=cur, error=str(e)[:200])
    for f in candidates:
        try:
            f.decrypt(token_bytes)
            return True
        except InvalidToken:
            continue
    return False


def encrypt_config(config: dict, tenant_id: str = None) -> str:
    """Encrypt a tenant config dict to a version-tagged Fernet token string.

    Always writes the CURRENT generation tag (``v<N>:``).

    Raises ``TenantCryptoError`` — in every deployment mode — when the current
    master key is missing, invalid, or was auto-generated in-process, rather
    than storing a row nobody can ever decrypt again (WO-H75).
    """
    cur = _current_generation()
    _assert_master_key_writable(cur)
    f = (_derive_tenant_fernet(tenant_id, cur)
         if tenant_id else _get_fernet(cur))
    plaintext = json.dumps(config, default=str).encode("utf-8")
    token = f.encrypt(plaintext).decode("utf-8")
    return f"v{cur}:{token}"


def decrypt_config(encrypted: str, tenant_id: str = None) -> dict:
    """Decrypt a (possibly version-tagged) Fernet token to a config dict.

    Resolution order for a tagged token at generation ``g``:
      1. per-tenant key derived from generation ``g``
      2. per-tenant key derived from the OTHER available generation (rotation)
      3. global (non-derived) master key of generation ``g`` — legacy data
         encrypted before per-tenant key derivation
      4. global master key of the OTHER generation

    Returns ``{}`` for empty input (legitimately-empty tenant config). Raises
    ``TenantCryptoError`` (a ``ValueError`` subclass) only on a GENUINE decrypt
    failure — wrong/rotated/corrupt token under every available key. Callers
    rely on this to fail closed; an empty config and a failed decrypt are
    distinct outcomes.
    """
    if not encrypted:
        return {}

    tagged_gen, token = _split_version(encrypted)
    token_bytes = token.encode("utf-8")

    # Candidate generations to try: the tagged one first, then the other
    # available master (so rotation works regardless of tag direction).
    cur = _current_generation()
    gens = [tagged_gen]
    for g in (cur, cur - 1):
        if g not in gens:
            gens.append(g)

    last_err: Exception | None = None

    for gen in gens:
        # (a) per-tenant derived key for this generation
        if tenant_id:
            try:
                f = _derive_tenant_fernet(tenant_id, gen)
            except KeyError:
                f = None  # generation's master not configured — skip
            except Exception as e:
                last_err = e
                f = None
            if f is not None:
                try:
                    return json.loads(f.decrypt(token_bytes))
                except InvalidToken as e:
                    last_err = e
                except json.JSONDecodeError as e:
                    # Decrypt succeeded but payload is not JSON — corrupt.
                    last_err = e

        # (b) global (non-derived) master key for this generation —
        # legacy data encrypted before per-tenant key derivation existed.
        try:
            f = _get_fernet(gen)
        except (KeyError, RuntimeError):
            f = None
        if f is not None:
            try:
                return json.loads(f.decrypt(token_bytes))
            except InvalidToken as e:
                last_err = e
            except json.JSONDecodeError as e:
                last_err = e

    logger.error("tenant_config_decrypt_failed",
                 tenant_id=tenant_id, error=str(last_err))
    raise TenantCryptoError(
        f"Failed to decrypt tenant config: {last_err}")
